<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/todo_services.proto

namespace Protobuf\Services;

if (false) {
    /**
     * This class is deprecated. Use Protobuf\Services\TodoPutRequest\Payload instead.
     * @deprecated
     */
    class TodoPutRequest_Payload {}
}
class_exists(TodoPutRequest\Payload::class);
@trigger_error('Protobuf\Services\TodoPutRequest_Payload is deprecated and will be removed in the next major release. Use Protobuf\Services\TodoPutRequest\Payload instead', E_USER_DEPRECATED);

