<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: services/todo_services.proto

namespace Protobuf\Services;

use Spiral\GRPC;
use Google\Protobuf;

interface TodoServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "services.TodoService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Protobuf\GPBEmpty $in
    * @return TodosResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ListTodos(GRPC\ContextInterface $ctx, Protobuf\GPBEmpty $in): TodosResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param TodoGetRequest $in
    * @return TodoResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetById(GRPC\ContextInterface $ctx, TodoGetRequest $in): TodoResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param TodoPutRequest $in
    * @return TodoResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function UpdateById(GRPC\ContextInterface $ctx, TodoPutRequest $in): TodoResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param TodoPostRequest $in
    * @return TodoResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function CreateTodo(GRPC\ContextInterface $ctx, TodoPostRequest $in): TodoResponse;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param TodoDestroyRequest $in
    * @return TodoResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function DestroyTodo(GRPC\ContextInterface $ctx, TodoDestroyRequest $in): TodoResponse;
}
