<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/todo_services.proto

namespace Protobuf\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.TodoResponse</code>
 */
class TodoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .entity.Todo todos = 1;</code>
     */
    private $todos;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Protobuf\Entity\Todo>|\Google\Protobuf\Internal\RepeatedField $todos
     * }
     */
    public function __construct($data = NULL) {
        \Protobuf\GPBMetadata\TodoServices::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .entity.Todo todos = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTodos()
    {
        return $this->todos;
    }

    /**
     * Generated from protobuf field <code>repeated .entity.Todo todos = 1;</code>
     * @param array<\Protobuf\Entity\Todo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTodos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protobuf\Entity\Todo::class);
        $this->todos = $arr;

        return $this;
    }

}

