<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/todo_services.proto

namespace Protobuf\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.TodoPutRequest</code>
 */
class TodoPutRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>.services.TodoPutRequest.Payload payload = 2;</code>
     */
    protected $payload = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type \Protobuf\Services\TodoPutRequest\Payload $payload
     * }
     */
    public function __construct($data = NULL) {
        \Protobuf\GPBMetadata\TodoServices::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.services.TodoPutRequest.Payload payload = 2;</code>
     * @return \Protobuf\Services\TodoPutRequest\Payload|null
     */
    public function getPayload()
    {
        return $this->payload;
    }

    public function hasPayload()
    {
        return isset($this->payload);
    }

    public function clearPayload()
    {
        unset($this->payload);
    }

    /**
     * Generated from protobuf field <code>.services.TodoPutRequest.Payload payload = 2;</code>
     * @param \Protobuf\Services\TodoPutRequest\Payload $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \Protobuf\Services\TodoPutRequest\Payload::class);
        $this->payload = $var;

        return $this;
    }

}

