<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity/error.proto

namespace Protobuf\GPBMetadata;

class Error
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
w
entity/error.protoentity"&
Error
code (
message (	B)ÊProtobuf\\EntityâProtobuf\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

