<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/todo_services.proto

namespace Protobuf\Services\TodoPutRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.TodoPutRequest.Payload</code>
 */
class Payload extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>bool is_complete = 3;</code>
     */
    protected $is_complete = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type string $name
     *     @type bool $is_complete
     * }
     */
    public function __construct($data = NULL) {
        \Protobuf\GPBMetadata\TodoServices::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_complete = 3;</code>
     * @return bool
     */
    public function getIsComplete()
    {
        return $this->is_complete;
    }

    /**
     * Generated from protobuf field <code>bool is_complete = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsComplete($var)
    {
        GPBUtil::checkBool($var);
        $this->is_complete = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Payload::class, \Protobuf\Services\TodoPutRequest_Payload::class);

